### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Gargo** [p0nce/aliasthis#4]
Fetching derelict-util 2.0.6 (getting selected version)...
Fetching ae-graphics 0.0.9 (getting selected version)...
Fetching msgpack-d 1.0.0-beta.2 (getting selected version)...
Fetching derelict-sdl2 1.9.7 (getting selected version)...
Fetching logger 2.66.0 (getting selected version)...
Fetching gfm 2.3.37 (getting selected version)...
Invalid source/import path: C:\Users\╨Р╨┤╨╝╨╕╨╜╨╕╤Б╤В╤А╨░╤В╨╛╤А\AppData\Roaming\dub\packages\logger-2.66.0\logger\std\experimental\logger
Invalid source/import path: C:\Users\╨Р╨┤╨╝╨╕╨╜╨╕╤Б╤В╤А╨░╤В╨╛╤А\AppData\Roaming\dub\packages\logger-2.66.0\logger\std\experimental\logger
Invalid source/import path: C:\Users\╨Р╨┤╨╝╨╕╨╜╨╕╤Б╤В╤А╨░╤В╨╛╤А\AppData\Roaming\dub\packages\logger-2.66.0\logger\std\experimental\logger
Invalid source/import path: C:\Users\╨Р╨┤╨╝╨╕╨╜╨╕╤Б╤В╤А╨░╤В╨╛╤А\AppData\Roaming\dub\packages\logger-2.66.0\logger\std\experimental\logger
Performing "debug" build using dmd for x86.
gfm:core 2.3.37: building configuration "library"...
Error: module memory is in file 'C:\Users\╨Р╨┤╨╝╨╕╨╜╨╕╤Б╤В╤А╨░╤В╨╛╤А\AppData\Roaming\dub\packages\gfm-2.3.37\gfm\core\gfm\core\memory.d' which cannot be read
import path[0] = C:\Users\╨Р╨┤╨╝╨╕╨╜╨╕╤Б╤В╤А╨░╤В╨╛╤А\AppData\Roaming\dub\packages\gfm-2.3.37\gfm\core
import path[1] = E:\D\dmd2\windows\bin\..\..\src\phobos
import path[2] = E:\D\dmd2\windows\bin\..\..\src\druntime\import
dmd failed with exit code 1.

**Comment by p0nce** [comment]
Currently upgrading to modern day dependencies.

**Comment by p0nce** [comment]
Fixed
